# training options for baseline

model_dir: models

train:
  batch_size: 80
  batch_tokens_size:
  save_checkpoint_steps: 1000
  train_steps:
  eval_steps: 100
  maximum_features_length: 50
  maximum_labels_length: 50
  shuffle_every_epoch:

